### PR TITLE
Don't set shell to /bin/sh on Windows

### PR DESCRIPTION
**Pull request by ljani**
Don't set shell to `/bin/sh` on Windows. Setting the shell to `sh` on Windows breaks eg. Vundle. Shell should default to  `%comspec%` on Windows.. I'm not sure if there's any help setting it to `cmd.exe` explicitly, so there's no point touching it on Windows.

### CODE REVIEW

**Comment by teasp00n** [comment]
Agreed. My shell is actually /usr/bin/sh so I had to override this locally anyway. I think if people are using 'non standard' shells then they will probably be aware they need to make alterations in their local vimrc.

**Comment by Gaelan** [comment]
@teasp00n The problem is, editing vimrc (not .local) makes updates harder.

**Comment by teasp00n** [comment]
@GaelanS Sorry I should have been more clear, when I said local vimrc I meant vimrc.local.

**Comment by Gaelan** [comment]
Ah. But vim was erroring (I assume) before vimdc.local got loaded.

**Comment by teasp00n** [comment]
Oh OK. I didn't get that although I'm not using windows however /bin/sh is not where my shell executable is. In any case I don't think setting the shell in the .vimrc like that is really suitable across all environments. Ideally it would use the $PATH to find it and if people have custom setups, defer the configuration to the .vimrc.local.

**Comment by spf13** [comment]
What if you put that line in your vimrc.bundles.local? That loads a lot

## earlier.

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by teasp00n** [comment]
@spf13 Adding `set shell=/usr/bin/sh` to my .vimrc.local did fix my issue by the way. Not sure if you were talking to me or not...

**Pull request merged**
