### PR TITLE
Closing Issue #400; Fixing installer script of spf13-vim

### PR DESCRIPTION
**Pull request by X4**
This pull-request refers to https://github.com/spf13/spf13-vim/issues/400
Please try it out, before you apply it. I don't have a Mac and can't test if it works on OSX.

### CODE REVIEW

**Comment by X4** [comment]
It works perfectly for me, please test it on your box and tell me if it works on osx too.
I reported an error in vundle, it breaks the .vimrc when run twice, because it doesn't check if a plug-in is already installed or not. Vundle blindly re-applies everything.

_wish someone teached me vim a little, I'm poor at it and :vimtutor didn't really help_

**Comment by X4** [comment]
Bump?

**Comment by spf13** [comment]
Just testing still.

Steve Francia
spf13.com
@spf13

On Jul 17, 2013, at 5:07 PM, Ferhat notifications@github.com wrote:

Bump?

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/pull/403#issuecomment-21154599
.

**Comment by X4** [comment]
Thanks Steve, let me know if something needs to be changed. Initially I wanted to integrate a report service to track failed installs, but left that out, because that would be :100:  overkill and only take precious time debugging it until it works :)

**Comment by spf13** [comment]
Everything looks very good and I'm very excited and grateful for this
contribution.
The changeset is however very large, so I want to spend more time to test
it across a few environments.

**Comment by X4** [comment]
You could add which platforms this script was tested on and that in case it doesn't work with someone's platform, because he's missing "bash", then you could still refer to the old script, manual instructions or I can write a "lite" script.

**Comment by X4** [comment]
Tested on Sabyon and Gentoo linux here.

**Comment by spf13** [comment]
It ran fine on my macbook, but not so well on my ubuntu box.

Ubuntu 12.04

```
sh spf13-vim.sh 
spf13-vim.sh: 4: spf13-vim.sh: Syntax error: "(" unexpected
parallels@parallels-Parallels-Virtual-Platform:~/code$ bash --version
GNU bash, version 4.2.24(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by X4** [comment]
@spf13 OK, that was an issue because the shebang line defaulted to sh on your ubuntu machine. That should be fixed now, because now bash is required to run the script. Let me know if it works now and please retest on your mac too. It still works on my machine.

**Comment by X4** [comment]
Hi @spf13,

do you have any news? Did it work?

**Comment by X4** [comment]
re

**Comment by spf13** [comment]
Should merge later today. Just doing some final testing.

**Comment by spf13** [comment]
It still didn't work. I ended up rewriting it to be posix compliant so it works in sh, dash, bash and zsh.. possibly even fish. I'll merge this then commit that.

**Comment by X4** [comment]
awesome!

**Pull request merged**
