### PR TITLE
Updated HTML-AutoCloseTag

### PR DESCRIPTION
**Pull request by mmjmanders**
amirh's HTML-AutoCloseTag repo doesn't exist anymore

### CODE REVIEW

**Comment by yudenzel** [comment]
Could we replace it with vim-scripts/HTML-AutoCloseTag ?

**Comment by chrisnicola** [comment]
There have been reports this plugin does not work #552. Can someone verify that it does otherwise we should just remove it as was suggested a couple of years ago.

**Comment by ProteusCortex** [comment]
There is a mirror of the original plugin [here](https://github.com/vim-scripts/HTML-AutoCloseTag), although @amirh's fork had a fix not present in this repo.

**Comment by ghost** [comment]
yes I am having problems with HTML-AutoCloseTag. when I update my plugins, it cannot update the plugin. (using Lnx and vim 8)

**Comment by ghost** [comment]
Does any one have an alternative of the plugin that can be used. I am checking around and wondering if anyone have a suggestion.

**Comment by kenips** [comment]
@chrisnicola I can confirm that HTML-AutoCloseTag still works and this PR fixes the source issue.

**Comment by conrado** [comment]
repositories on https://github.com/vim-scripts don't get curated (PR's looked at, etc) I would recommend using a location like https://github.com/heracek/HTML-AutoCloseTag

**Pull request closed without merging**
