### PR TITLE
Added the VDebug multi-purpose debugger

### PR DESCRIPTION
**Pull request by mmikitka**
VDebug is an amazing multi-language Vim debugger. It is a complete re-write of the Xdebug project with several additions: no error messages, abstracted configuration and code-base, supports multiple languages (PHP, Python, Ruby, Perl, Tcl, JavaScript), the documentation is clean, and the UI is clean and consistent.

See ":help vdebug" for more information.

I applied the following overrides to my .vimrc.bundles.local file.

" Vdebug {
    let g:vdebug_options= {
    \    "port" : 9000,
    \    "server" : '205.189.23.105',
    \    "timeout" : 20,
    \    "on_close" : 'detach',
    \    "ide_key" : '1',
    }

```
" Map the key bindings to Firebug
let g:vdebug_keymap = {
\    "run_to_cursor" : "<F1>",
\    "set_breakpoint" : "<F4>",
\    "run" : "<F5>",
\    "close" : "<F6>",
\    "detach" : "<F7>",
\    "get_context" : "<F8>",
\    "eval_under_cursor" : "<F9>",
\    "step_over" : "<F10>",
\    "step_into" : "<F11>",
\    "step_out" : "<S-F11>",
\}
```

" }

### CODE REVIEW

**Comment by spf13** [comment]
To merge this I'd really like an update to the readme with instructions to setting it up since it doesn't just work out of the box.

**Comment by johntyree** [comment]
I'm not sure if "voting" on things is the norm really, but I vote no on this one. This is a really niche plugin. It only works on a few scripting languages (no C, C++, Java, .NET... etc) and only with a binary third-party blob from ActiveState. This should be opt-in at most, but probably just belongs in `.vimrc.bundles.local`.

Additionally getting it working is not straightforward. At the moment I'm playing with the Python client and it fails to start because of missing libs. Is it supposed to require python3? @mmikitka, which language are you using this with?

**Comment by mmikitka** [comment]
@johntyree I have only used vdebug with PHP, and in my opinion, it is by far the most stable and robust Vim-PHP debugger.

@spf13 I can put together a readme. Also, I am not bothered if this stays in .vimrc.bundles.local.

**Comment by johntyree** [comment]
It also apparently activates for all filetypes and clobbers keybindings, regardless of whether or not it can do anything. I was setting breakpoints in LaTeX files :D

@mmikitka If you do write something about it, maybe investigate how to get it to play nicely when it's not needed?

**Comment by spf13** [comment]
Closing for now.

**Pull request closed without merging**
