### PR TITLE
map `\` to `,`, becase <leader> takes `,`

### PR DESCRIPTION
**Pull request by e7h4n**

### CODE REVIEW

**Comment by mikedfunk** [comment]
+1 I do this already in .vimrc.local

## 

_Mike Funk_
mikefunk.com | mike@mikefunk.com

**Comment by johntyree** [comment]
Is this just for working around broken plugins that don't honor `<leader>` ?

**Comment by e7h4n** [comment]
Accurately map `\` will not affect any maps like `\a` or `\b`.

**Comment by MattWoelk** [comment]
Do you mean something like this? (From my .vimrc.local)

```
noremap \ ,
```

**Comment by johntyree** [comment]
I'm totally against indiscriminately remapping a key like this.

Some plugins use `\` instead of `<leader>` which is annoying, but sometimes people (myself included) use `\` for other things. This kind of mapping belongs in your personal `.vimrc.local`.

What problem is this solving? Maybe I'm just not understanding you correctly.

**Comment by spf13** [comment]
I agree with @johntyree Best in local.

**Pull request closed without merging**
