### PR TITLE
Fixed case of "leader"

### PR DESCRIPTION
**Pull request by krymen**
Fixed "leader" from upper to lower case in `.vimrc` file.

### CODE REVIEW

**Comment by spf13** [comment]
Why do this? In almost all the documentation I've seen it's initial capped. Is there any benefit to doing this?

**Comment by krymen** [comment]
Well, in my vim (on Ubuntu) initial capped doesn't work.

**Comment by krymen** [comment]
I've just checked if `<Leader>` really doesn't work. It works only if I type `:source ~/.vimrc`. Same with `<leader>`. 

Seems that problem lies elsewhere. @spf13 Do you have any idea?

**Comment by spf13** [comment]
Does it load the rest of your .vimrc file appropriately? Very odd that this one section would be ignored unless you source it.

Best,
Steve

http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by krymen** [comment]
Seems that everything else works after lunching vim.

**Pull request closed without merging**
