### PR TITLE
Absolute line numbers in insert mode, and relative in normal mode.

### PR DESCRIPTION
**Pull request by trantorLiu**
Issue #355.

### CODE REVIEW

**Comment by johntyree** [comment]
`myusuf3/numbers.vim` already handles this and is included by default. Are you using a recent pull? In my setup it's in `.vimrc.bundles` line 99.

**Comment by trantorLiu** [comment]
Yeah, but the line numbers are still relative in insert mode right?

**Comment by johntyree** [comment]
Not for me. Let me check, maybe I made this change myself somewhere...

**Comment by johntyree** [comment]
Nope that's the plugin. If you check `:he numbers` you'll see it's right in the first sentence.

**Comment by trantorLiu** [comment]
OK, my mistake.

**Comment by johntyree** [comment]
Did you get it working?

**Comment by trantorLiu** [comment]
Yes, that was totally my mistake. Sorry.

**Pull request closed without merging**
