### PR TITLE
Cross buffer search

### PR DESCRIPTION
**Pull request by jeromer**
Hi Steve,

You will find in rev e118e5ec the cross buffer search I sent you over twiter yesterday.

This is the first time I use the pull request feature so in case you can not cherry-pick changeset e118e5ec     just let me know and I'll sort that out.

Have a nice day :)

### CODE REVIEW

**Comment by spf13** [comment]
Can't merge this in. Commit 699845a breaks everything. Really just want e118e5e. Either make a new pull request, or let me know and I'll try to cherry pick from that single commit.

**Comment by jeromer** [comment]
Sorry the merge breaks everything. Do you mind to cherry pick e118e5e ?

**Comment by jamestomasino** [comment]
I'll pull out [e118e5e](https://github.com/spf13/spf13-vim/commit/e118e5e) and make a new pull request. It's a simple change. I'd rather clean up the Pull Requests lists.

**Comment by jamestomasino** [comment]
My [pull request](https://github.com/spf13/spf13-vim/pull/209) is submitted. It is the cherry-picked contents of [e118e5e](https://github.com/spf13/spf13-vim/commit/e118e5e) in a nice clean pull request. Hopefully this will allow you to close both requests. Thanks.

**Comment by spf13** [comment]
Thanks. I've merged in that pull request and will close this one.

**Pull request closed without merging**
