### PR TITLE
add app_dir var to point to root of application

### LINKED ISSUE #548: on changing the app base directory ($HOME/.spf13-vim-3)
I was about to submit a PR that added `base_dir` to bootstrap.sh set to `$HOME/.spf13-vim-3` by default, (to match the `%BASE_DIR%` env var in the windows install scripts) but it seemed like this had already been previously the case with the endpath variable and was removed in this changeset https://github.com/spf13/spf13-vim/commit/7677bdaf86af1be8f8af9db960de8ac2311a4f18 . Is there any reason we can't shouldn't have this variable as long as we keep this: `endpath="$( cd "$( dirname "$0" )" && pwd)"`?

### PR DESCRIPTION
**Pull request by ghost**
This should fix #548

We could still rename the other endpath variables, but i plan
on doing something with them in future commits.

### CODE REVIEW

**Comment by johntyree** [comment]
Looks reasonable to me.

**Comment by ghost** [comment]
well merge when you're ready then (unless you want endpath renamed now)

**Comment by johntyree** [comment]
I'd like to test it at least once before merging, unfortunately that will have to wait for the weekend when I have some free time.

**Comment by spf13** [comment]
I'm in the same boat as @johntyree .. might not even be able to get to it until next week. Sounds like one of us will get to it this weekend. Thanks for the solid contributions.

**Pull request merged**
