### PR TITLE
Add way to toggle background light or dark

### PR DESCRIPTION
**Pull request by cljoly**
There is maybe a better place for this.

I'm a VimL beginner, I hope my code is correct. At home, it works.

### CODE REVIEW

**Comment by barraponto** [comment]
I like this.

**Comment by cljoly** [comment]
Thanks!

**Comment by barraponto** [comment]
@leowzukw @spf13 i like this, but I think `<Leader>b` is already used by python-mode.
maybe that's why it doesn't work in my install.

**Comment by cljoly** [comment]
@barraponto `<leader>bg` would be a good option too, since it should not be used everytime.

**Comment by barraponto** [comment]
@leowzukw yeah but when you type `<Leader>bg` you trigger the python mode `<Leader>b` before it gets the `g`. So, in other words, it doesn't work as is :-1:

**Comment by spf13** [comment]
I don't do much python now a days so it worked for me. We could change it... but to what? Also what does <leader>b do in python? Should we change that?

**Comment by cljoly** [comment]
@barraponto Why not `<leader>tbg`, if it is not used already.

Does it let anything free :smile: ?

**Pull request merged**
