### PR TITLE
Airline: Configure to Look More Like Powerline

### PR DESCRIPTION
**Pull request by jcbwlkr**
I like the speed and lack of dependencies of vim-airline but I prefer the look of powerline. I added a theme "powerlineish" to vim-airline that mimics the colors of classic powerline. This commit enables that theme and enables the use of powerline fonts to get the nice separators.

I wasn't sure if this should go in `.vimrc` in the status line section or in `.vimrc.bundles`. I opted for the latter so the variables are only set if you're actually using that bundle. Additionally I considered adding a configuration variable to enable the powerline fonts but ultimately decided against it.

### CODE REVIEW

**Comment by jcbwlkr** [comment]
@spf13 moved to vimrc

**Comment by ngaloppo** [comment]
Is there a way we can check if the powerline patched fonts have been installed? Alternatively, can you suggest a .vimrc.local / .gvimrc.local approach that would let me use the same *.local files across systems that may or may not have have these fonts installed? Thanks!

**Comment by spf13** [comment]
No way to tell from inside vim. Could do as part of the installer maybe,
but that doesn't handle the case where they install it afterwards.

As for the locals, you are talking about a Fork in spf13-vim terminology
and its totally supported.

Steve Francia
spf13.com
@spf13

On Aug 13, 2013, at 3:34 AM, ngaloppo notifications@github.com wrote:

Is there a way we can check if the powerline patched fonts have been
installed? Alternatively, can you suggest a .vimrc.local / .gvimrc.local
approach that would let me use the same *.local files across systems that
may or may not have have these fonts installed? Thanks!

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/pull/413#issuecomment-22547829
.

**Comment by spf13** [comment]
The installer could potentially install the font as well, but it currently
doesn't do anything like that so it would be a lot of work to do that cross
platform.

Steve Francia
spf13.com
@spf13

On Aug 13, 2013, at 7:20 AM, Steve Francia steve.francia@gmail.com wrote:

No way to tell from inside vim. Could do as part of the installer maybe,
but that doesn't handle the case where they install it afterwards.

As for the locals, you are talking about a Fork in spf13-vim terminology
and its totally supported.

Steve Francia
spf13.com
@spf13

On Aug 13, 2013, at 3:34 AM, ngaloppo notifications@github.com wrote:

Is there a way we can check if the powerline patched fonts have been
installed? Alternatively, can you suggest a .vimrc.local / .gvimrc.local
approach that would let me use the same *.local files across systems that
may or may not have have these fonts installed? Thanks!

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/pull/413#issuecomment-22547829
.

**Comment by ngaloppo** [comment]
In that case we should probably default to g:airline_powerline_fonts=0 in
.vimrc.

**Comment by qva5on3** [comment]
If by default configuration would set 
`g:airline_powerline_fonts=0`
I suggest at least adding a comment explaining its purpose.

**Comment by jcbwlkr** [comment]
@spf13 As others have mentioned above maybe we should turn the nice fonts back off. There have been a few issues filed recently from users without the fonts installed.

Perhaps we could disable the fonts but add a section to the README with screenshots showing what it looks like and how to enable them?

**Comment by spf13** [comment]
I think that's a good idea. Pull request?

Steve Francia
spf13.com
@spf13

On Aug 21, 2013, at 8:28 AM, Jacob Walker notifications@github.com wrote:

@spf13 https://github.com/spf13 As others have mentioned above maybe we
should turn the nice fonts back off. There have been a few issues filed
recently from users without the fonts installed.

Perhaps we could disable the fonts but add a section to the README with
screenshots showing what it looks like and how to enable them?

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/pull/413#issuecomment-23013347
.

**Comment by jcbwlkr** [comment]
I'll get on that.

**Comment by jcbwlkr** [comment]
For those following this thread please reference the new PR #428.

**Pull request merged**
