### PR TITLE
Fix .nvimrc symlink on bootstrap

### PR DESCRIPTION
**Pull request by agonzalezro**

### CODE REVIEW

**Comment by bronzehedwick** [comment]
+1 yikes I made a bad merge

**Comment by ghost** [comment]
I thought that was on purpose, since it should read nvimrc from there shouldn't it?

**Comment by ghost** [comment]
regular vim doesn't need ~/.vimrc since 7.4, it will happily read ~/.vim/vimrc or so the docs say if (~/.vimrc doesn't exist).

**Comment by bronzehedwick** [comment]
Ack that's right. Can't keep my head straight.

**Comment by agonzalezro** [comment]
The "old" style (`~/vimrc`) is being used for vim: https://github.com/agonzalezro/spf13-vim/blob/patch-1/bootstrap.sh#L124

Sadly, I've clear my history already, but that line was failing. Checking the code is weird because `~/.vim` is a folder linked to `~/.nvim` and the `~/.nvim/.nvimrc` should be allowed, but as I said, the link was failing.

**Comment by ghost** [comment]
and now this PR is obsolete for neovim due to the usage of XDG paths

**Comment by agonzalezro** [comment]
I didn't even remember that this was open. Feel free to close it. Thanks.

**Pull request closed without merging**
