### PR TITLE
Refactor/cleanup bootstrap.sh

### PR DESCRIPTION
**Pull request by ghost**
Summary
- simplify the various functions that call git commands
- pass arguments to functions instead of relying on global variables
- show *vimrc files that are being backed up
- remove trailing white space
- harmonize output messages
- harmonize indentation in the MAIN section
- color codes that work in dash (the ubuntu default shell)
- add REPO_URI, REPO_BRANCH, and APP_PATH env variables

I didn't remove the use of global $ret in  debug(),error(), and success() because i didnt
 think it wouldn't add much value, but i could add that for consistency.

You can test it by running this command

```
REPO_BRANCH="cleanup-bootstrap" REPO_URI='https://github.com/jrobeson/spf13-vim.git'   sh <(curl https://raw.githubusercontent.com/jrobeson/spf13-vim/cleanup-bootstrap/bootstrap.sh -L)
```

These changes are one step towards making it easy to use a different directory structure
out of the box instead of dropping all the files in $HOME

I will rebase/squash these changes if requested

### CODE REVIEW

**Comment by mikedfunk** [comment]
+1

## 

_Mike Funk_
mikefunk.com | mike@mikefunk.com

**Comment by ghost** [comment]
i'm currently making more of the top level variables settable in the environment, but maybe they should be parameters instead. Seems like it wouldn't work so well with the easiest installation option though.

**Comment by ghost** [comment]
updated the PR description with new ENV vars and instructions on how to test.

**Comment by ghost** [comment]
@spf13: can you take a look at this?

**Comment by ghost** [comment]
i'm confused as to what ~/.vim is actually supposed to be linked to since it doesn't exist by default. seems to have been an issue for awhile.

**Comment by tebowy** [comment]
What about spf13-vim residing in ~/.vim? I think this could be a better place than current custom directory (spf13-vim is suposed to be, after all, a config)

**Comment by spf13** [comment]
~/.vim is where the plugins typically go for a vim installation. I'm fine with moving spf13-vim dir into that provided it's backed up properly first.

**Comment by spf13** [comment]
@jrobeson These changes look quite good in general. I'm going to merge it in a branch to play with it before merging the pull request.

**Comment by tebowy** [comment]
By _backing up properly_ you mean making a copy, or a statement about merits of something?

**Comment by spf13** [comment]
Maybe I'm confused about this thread. The current implementation is designed to be easily reversible and uninstallable.

Everything is installed into ~/.spf13-vim-3 . Then old paths are backed up (moved) and replaced with symlinks into the ~/.spf13-vim-3 directory.

Mine looks like:

.vim -> /Users/spf13/.spf13-vim-3/.vim
.vimrc -> /Users/spf13/.spf13-vim-3/.vimrc
.vimrc.before -> /Users/spf13/.spf13-vim-3/.vimrc.before
.vimrc.before.local
.vimrc.bundles -> /Users/spf13/.spf13-vim-3/.vimrc.bundles
.vimrc.bundles.local
.vimrc.local

I think this works well. An uninstall is as simple as removing the .spf13-vim-3 directory and moving back the backed up files. 

What's the question about the .vim directory. I don't think I understood that fully. 

My comment was that we could just install spf13-vim into the .vim directory, but to do so would require us to still create all the symlinks (or at least the .vimrc one). We'd also need to provide an upgrade path as part of the installer. Make it seamless so just rerunning the installer would move things into the new paths.

**Comment by tebowy** [comment]
Ah, sorry for confusion, sometimes my English is making out of control. You've already answered my question above, (_The current implementation is designed to be easily reversible and uninstallable. (…) An uninstall is as simple as removing the .spf13-vim-3 directory and moving back the backed up files._).  I am not going to bother anymore about this.

Actually, though, at least with vim 7.4, you don't have to create `~/.vimrc → ~/.vim/.vimrc` (or `~/.vimrc → ~/.vim/vimrc`) symlinks. Vim will pick one of these by itself. Please look at [this commit](https://github.com/szymonszydelko/vim/commit/4acebd4ff0b151291abb09be6df774b379815003) -- it work just fine. (I just don't happen to like `.` files directly in my `~`). ;)

**Comment by spf13** [comment]
If we can keep it all in the one directory that would be far cleaner.. Vim still looks to ~/.vimrc first though so we would need to move everything that is in the places vim looked prior to inside ~/.vim/ . Then there's the problem of least expectation.. Most people expect the config to be ~/.vimrc. If they can't find it there, they will be confused.

**Comment by tebowy** [comment]
> If we can keep it all in the one directory that would be far cleane

This is exactly why I've proposed the move.

>  Most people expect the config to be ~/.vimrc. If they can't find it there, they will be confused.    

Well, you have too much right. I think this one is actually quite… unapproachable issue.

**Comment by ghost** [comment]
We could create the .vimrc on first install and then not recreate it on update if it doesn't exist.

EDITED: removed something already said.

**Comment by ghost** [comment]
@spf13 : the main outstanding issue (which existed previously) is the  current symlinking of ~/.vim .

It currently does nothing useful.

I'd like to continue discussion on how to adapt to different directory structures to another ticket.
The goal for this was just to clean up what we already have.

**Comment by ghost** [comment]
Oh, and if you have any thoughts on the usage of environment vars vs actual arguments that'd be good too. I just added environment variables because that's what already existed

**Comment by spf13** [comment]
I agree. Let's move the dialogue to a different ticket and improve what we have.

**Comment by ghost** [comment]
@spf13: so did it work out for you? anything you want me to change?

**Comment by spf13** [comment]
@jrobeson. I'm giving 3 talks at OSCON in a week. I won't have time I need to dedicate to this until after that. Will look into it the following week.

**Comment by ghost** [comment]
ping ?

**Comment by ghost** [comment]
@spf13 : ping?

**Comment by spf13** [comment]
I suck. I'll review this week. 
As long as you are committing to support if any issues come up, I'm happy to merge it after I review it.

**Comment by ghost** [comment]
@bronzehedwick : what do you think?

**Comment by bronzehedwick** [comment]
@jrobeson I love this improvement's move towards greater flexibility. I took it for a spin on Mac OS X 10.10.1 and MacVim 7.4, and it worked fine.

**Pull request merged**
