### PR TITLE
added BundleInstall to the windows installer .cmd file

### PR DESCRIPTION
**Pull request by jhnwsk**
Hi Steve,

I installed on XP today and found that for some reason the .cmd script does not call BundleInstall. After I launched vim it threw lots of red letters at me.

Fix is pretty simple. I tested on XP only.

cheers,
John

### CODE REVIEW

**Comment by jhnwsk** [comment]
I think this behaviour is the reason for #167.

**Comment by kew-l** [comment]
Wouldn't this need '-u "$BASE_DIR/.vimrc.bundles"' fed in as well?

call vim -u "$BASE_DIR/.vimrc.bundles" - +BundleInstall! +BundleClean +qall

**Comment by spf13** [comment]
I'm traveling and won't be back to my windows machine for a couple days so really appreciate the help from others.   

This is accurate and should match the final call in the bootstrap.sh  

## 

Steve Francia
@spf13

**Comment by jhnwsk** [comment]
Yeap you are right Kevin.

**Pull request merged**
