### PR TITLE
Changed solarized options from high to normal.

### PR DESCRIPTION
**Pull request by teasp00n**

### CODE REVIEW

**Comment by dtgay** [comment]
Big :+1: from me. I spent a good deal of time trying to figure out how to just disable the bright red/orange indent highlights, but when I found this fix I decided to keep them since they aren't eye-burning at normal solarization levels. :cocktail:

**Comment by spf13** [comment]
It's a good commit, just doesn't cleanly merge, so it will take me a bit to apply it.

**Comment by dtgay** [comment]
Perhaps you could just do it manually in the current `.vimrc`? Both lines are right next to each other still. You could still give @teasp00n credit in the commit message or pull request. :smile:

**Comment by teasp00n** [comment]
Doesn't bother me. If it's going to be a hassle to merge it then feel free to re-implement it on HEAD.

**Pull request merged**
