### PR TITLE
Updating powerline bundle

### PR DESCRIPTION
**Pull request by lucascaton**

### CODE REVIEW

**Comment by lucascaton** [comment]
Nevermind "/

There is a warning in old repository: "Plugin is currently in maintenance mode, no feature requests will be accepted. Vim-powerline will be deprecated in favour of https://github.com/Lokaltog/powerline once it is ready."

**Comment by Lokaltog** [comment]
The readme is a bit outdated. The old powerline project is abandoned and no longer maintained, and any users should update to the new project.

**Comment by lucascaton** [comment]
Nice @Lokaltog ;)

I'll reopen the pull request :-)

**Comment by mikedfunk** [comment]
:+1: I replaced vim-powerline with powerline. It's nicer.

**Comment by spf13** [comment]
This has been superseded by a different commit that does similar things, but with conditional fallback when Python isn't present.

**Pull request closed without merging**
