### PR TITLE
Provide ability to revert back to the previous version of powerline

### PR DESCRIPTION
**Pull request by mmikitka**

### CODE REVIEW

**Comment by johntyree** [comment]
I don't see why this shouldn't be an option, but why are you interested in preserving the old powerline plugin even when Vim has python support?

**Comment by mmikitka** [comment]
@johntyree I encountered character rendering problems in my terminal, and I am also happy with the current implementation and not ready to switch to a brand new extension that does not have as much mileage.

**Comment by johntyree** [comment]
You can set the characters manually to just use `|` like before. As for the missing features, _that_ is pretty annoying so far. Taking a peek at the powerline repo suggests that they are coming down the line eventually, though.

**Comment by spf13** [comment]
This powerline shift has caused a ton of issues for people. I'm happy to let people override to use the more tried and true one.

**Comment by johntyree** [comment]
It was annoying for me to get the fancy characters correct as well. Considering I don't use powerline in any other apps, I'd honestly rather the old one stay maintained. Hopefully it doesn't rot too quickly.

**Pull request merged**
